#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill ~/Pictures/bEAJ1NW.png
killall polybar
bspc config focused_border_color = "#692F45"
bspc config focused_border_color        "#00acc1" 
# bspc config focused_border_color        "#ff3465" 
# bspc config focused_border_color        "#ffffff" 
# bspc config focused_border_color        "#504945"
bspc config normal_border_color         "#1e0f2c"
bspc config active_border_color         "#fb4934"
# bspc config active_border_color         "#230B52"
bspc config presel_feedback_color		"#4c566a"
polybar main --config=/usr/share/doc/polybar/polybar/docky/config.ini
sh -c "rclone --vfs-cache-mode writes mount onedrive: ~/OneDrive"
picom
