#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI  

bspc config border_width         2
bspc config window_gap         6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config active_border_color = "#99d1ce"
feh --bg-fill ~/.config/roof.jpg
dunst
xinput set-prop 13 311 1 
picom
setxkbmap -layout dvorak
blight -d amdgpu_bl1 set 30
killall polybar
 bspc config focused_border_color        "#eceff4"
#bspc config normal_border_color         "#1e0f2c"
polybar main --config=~/.config/polybar/polybar
rclone --vfs-cache-mode writes mount onedrive: ~/OneDrive
xinput set-prop 13 306 1
# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd
